package shopping_cart;


import shopping_cart.laundary;
import java.awt.Image;
import javax.swing.*;
//import javax.

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class laundary extends javax.swing.JFrame {
    static int id = 100;
    /**
     * Creates new form productsPage
     */
    String[][] arr1 = new String[6][4];
    public laundary() {
        initComponents();        
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        price4 = new javax.swing.JLabel();
        price5 = new javax.swing.JLabel();
        price6 = new javax.swing.JLabel();
        switchCategories = new javax.swing.JToggleButton();
        prod4 = new javax.swing.JLabel();
        prod6 = new javax.swing.JLabel();
        addToCart5 = new javax.swing.JButton();
        addToCart6 = new javax.swing.JButton();
        addToCart7 = new javax.swing.JButton();
        prod7 = new javax.swing.JLabel();
        prod8 = new javax.swing.JLabel();
        prod9 = new javax.swing.JLabel();
        price7 = new javax.swing.JLabel();
        price8 = new javax.swing.JLabel();
        price9 = new javax.swing.JLabel();
        addToCart8 = new javax.swing.JButton();
        addToCart9 = new javax.swing.JButton();
        addToCart10 = new javax.swing.JButton();
        prod10 = new javax.swing.JLabel();
        gotoCart = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        q1TXT = new javax.swing.JTextField();
        q2TXT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        q3TXT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        q4TXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        q5TXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        q6TXT = new javax.swing.JTextField();
        price10 = new javax.swing.JLabel();
        price11 = new javax.swing.JLabel();
        price12 = new javax.swing.JLabel();
        price13 = new javax.swing.JLabel();
        price14 = new javax.swing.JLabel();
        price15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundary");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        price4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price4.setText("Comforter");

        price5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price5.setText("Towel");

        price6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price6.setText("Clips");

        switchCategories.setBackground(new java.awt.Color(204, 204, 204));
        switchCategories.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        switchCategories.setText("Switch Categories");
        switchCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchCategoriesActionPerformed(evt);
            }
        });

        ImageIcon icon3 =new ImageIcon("./images/laundary_4.jpg");
        Image img3=icon3.getImage();
        Image imageScale3=img3.getScaledInstance(97,89,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon3 =new ImageIcon(imageScale3);
        prod4.setIcon(scaledIcon3);

        ImageIcon icon5 =new ImageIcon("./images/laundary_6.jpg");                
        Image img5=icon5.getImage();                
        Image imageScale5=img5.getScaledInstance(97,89,Image.SCALE_SMOOTH);                
        ImageIcon scaledIcon5 =new ImageIcon(imageScale5);       
        prod6.setIcon(scaledIcon5);

        addToCart5.setBackground(new java.awt.Color(204, 204, 204));
        addToCart5.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart5.setText("Add to Cart");
        addToCart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart5ActionPerformed(evt);
            }
        });

        addToCart6.setBackground(new java.awt.Color(204, 204, 204));
        addToCart6.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart6.setText("Add to Cart");
        addToCart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart6ActionPerformed(evt);
            }
        });

        addToCart7.setBackground(new java.awt.Color(204, 204, 204));
        addToCart7.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart7.setText("Add to Cart");
        addToCart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart7ActionPerformed(evt);
            }
        });

        ImageIcon icon =new ImageIcon("./images/laundary_1.jpg");
        Image img=icon.getImage();
        Image imageScale=img.getScaledInstance(97,89,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon =new ImageIcon(imageScale);
        prod7.setIcon(scaledIcon);

        ImageIcon icon1 =new ImageIcon("./images/laundary_2.jpg");                
        Image img1=icon1.getImage();                
        Image imageScale1=img1.getScaledInstance(97,89,Image.SCALE_SMOOTH);                
        ImageIcon scaledIcon1 =new ImageIcon(imageScale1);       
        prod8.setIcon(scaledIcon1);

        ImageIcon icon2 =new ImageIcon("./images/laundary_3.jpg");                
        Image img2=icon2.getImage();                
        Image imageScale2=img2.getScaledInstance(97,89,Image.SCALE_SMOOTH);                
        ImageIcon scaledIcon2 =new ImageIcon(imageScale2);       
        prod9.setIcon(scaledIcon2);

        price7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price7.setText("Gloves");

        price8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price8.setText("Brush");

        price9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        price9.setText("Surf Excel");

        addToCart8.setBackground(new java.awt.Color(204, 204, 204));
        addToCart8.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart8.setText("Add to Cart");
        addToCart8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart8ActionPerformed(evt);
            }
        });

        addToCart9.setBackground(new java.awt.Color(204, 204, 204));
        addToCart9.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart9.setText("Add to Cart");
        addToCart9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart9ActionPerformed(evt);
            }
        });

        addToCart10.setBackground(new java.awt.Color(204, 204, 204));
        addToCart10.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        addToCart10.setText("Add to Cart");
        addToCart10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCart10ActionPerformed(evt);
            }
        });

        ImageIcon icons =new ImageIcon("./images/laundary_5.jpg");
        Image imgs=icons.getImage();
        Image imageScales=imgs.getScaledInstance(97,89,Image.SCALE_SMOOTH);
        ImageIcon scaledIcons =new ImageIcon(imageScales);
        prod10.setIcon(scaledIcons);

        gotoCart.setBackground(new java.awt.Color(204, 204, 204));
        gotoCart.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        gotoCart.setText("Go To Cart");
        gotoCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoCartActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantity:");

        q1TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1TXTActionPerformed(evt);
            }
        });

        q2TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2TXTActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantity:");

        q3TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3TXTActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity:");

        jLabel5.setText("Quantity:");

        jLabel6.setText("Quantity:");

        q5TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5TXTActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantity:");

        q6TXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6TXTActionPerformed(evt);
            }
        });

        price10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price10.setText("Rs.700");

        price11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price11.setText("Rs.200");

        price12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price12.setText("Rs.100");

        price13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price13.setText("Rs.700");

        price14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price14.setText("Rs.200");

        price15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        price15.setText("Rs.100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q3TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addToCart7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(price6)
                                .addComponent(price12))
                            .addComponent(prod9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price15)
                            .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q6TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(switchCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(gotoCart, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price13)
                            .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(q4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addToCart8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prod4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price10)
                                    .addComponent(price4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addToCart5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(prod7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(prod10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addToCart6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(price11)
                                        .addComponent(prod8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(price14)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q5TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31)
                                .addComponent(prod6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(addToCart10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(addToCart9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prod6, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(prod10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(price12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(price11)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(q2TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(q3TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addToCart7)
                            .addComponent(addToCart6))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(prod4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(q1TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(addToCart5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(prod9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price15, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(prod7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(prod8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(q4TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(q5TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(q6TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToCart8)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addToCart10)
                        .addComponent(addToCart9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchCategories)
                    .addComponent(gotoCart))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void switchCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchCategoriesActionPerformed
        // TODO add your handling code here:
          categories_page cp = new categories_page() ;
        cp.setVisible(true);
        this.setVisible(false);
      
//        Thread.sleep(2000);
    }//GEN-LAST:event_switchCategoriesActionPerformed

    private void addToCart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart5ActionPerformed
 if(evt.getSource() == addToCart5){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price4.getText().toString();
        String quantity_lbl = q1TXT.getText().toString();
        String price_lbl = price10.getText().toString();
        
    }
// addToCart("l04"); // TODO add your handling code here:
    }//GEN-LAST:event_addToCart5ActionPerformed

    private void addToCart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart6ActionPerformed
      
       if(evt.getSource() == addToCart6){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price5.getText().toString();
        String quantity_lbl = q2TXT.getText().toString();
        String price_lbl = price11.getText().toString();
//        Cart c1 = new Cart(id_value, name_lbl, quantity_lbl, price_lbl);
        
    }// TODO add your handling code here:
    }//GEN-LAST:event_addToCart6ActionPerformed

    private void addToCart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart7ActionPerformed
       
         if(evt.getSource() == addToCart7){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price6.getText().toString();
        String quantity_lbl = q3TXT.getText().toString();
        String price_lbl = price12.getText().toString();
//        Cart c1 = new Cart(id_value, name_lbl, quantity_lbl, price_lbl);
        
    } // TODO add your handling code here:
    }//GEN-LAST:event_addToCart7ActionPerformed

    private void addToCart8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart8ActionPerformed
      if(evt.getSource() == addToCart8){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price9.getText().toString();
        String quantity_lbl = q4TXT.getText().toString();
        String price_lbl = price13.getText().toString();
//        Cart c1 = new Cart(id_value, name_lbl, quantity_lbl, price_lbl);
        
    }        // TODO add your handling code here:
    }//GEN-LAST:event_addToCart8ActionPerformed

    private void addToCart9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart9ActionPerformed
         if(evt.getSource() == addToCart9){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price8.getText().toString();
        String quantity_lbl = q5TXT.getText().toString();
        String price_lbl = price14.getText().toString();
//        Cart c1 = new Cart(id_value, name_lbl, quantity_lbl, price_lbl);
        
    }   // TODO add your handling code here:
    }//GEN-LAST:event_addToCart9ActionPerformed

    private void addToCart10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCart10ActionPerformed
         if(evt.getSource() == addToCart10){
        id = id + 1;
        String id_value = Integer.toString(id);
        String name_lbl = price7.getText().toString();
        String quantity_lbl = q6TXT.getText().toString();
        String price_lbl = price15.getText().toString();
//        Cart c1 = new Cart(id_value, name_lbl, quantity_lbl, price_lbl);
        
    }   // TODO  // TODO add your handling code here:
    }//GEN-LAST:event_addToCart10ActionPerformed

    private void gotoCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoCartActionPerformed
Cart c=new Cart("","","","");
c.setVisible(true);
this.setVisible(false);
// TODO add your handling code here:    
    }//GEN-LAST:event_gotoCartActionPerformed

    private void q2TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2TXTActionPerformed

    private void q3TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3TXTActionPerformed

    private void q5TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5TXTActionPerformed

    private void q6TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6TXTActionPerformed

    private void q1TXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1TXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1TXTActionPerformed



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laundary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laundary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart10;
    private javax.swing.JButton addToCart5;
    private javax.swing.JButton addToCart6;
    private javax.swing.JButton addToCart7;
    private javax.swing.JButton addToCart8;
    private javax.swing.JButton addToCart9;
    private javax.swing.JToggleButton gotoCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel price10;
    private javax.swing.JLabel price11;
    private javax.swing.JLabel price12;
    private javax.swing.JLabel price13;
    private javax.swing.JLabel price14;
    private javax.swing.JLabel price15;
    private javax.swing.JLabel price4;
    private javax.swing.JLabel price5;
    private javax.swing.JLabel price6;
    private javax.swing.JLabel price7;
    private javax.swing.JLabel price8;
    private javax.swing.JLabel price9;
    private javax.swing.JLabel prod10;
    private javax.swing.JLabel prod4;
    private javax.swing.JLabel prod6;
    private javax.swing.JLabel prod7;
    private javax.swing.JLabel prod8;
    private javax.swing.JLabel prod9;
    private javax.swing.JTextField q1TXT;
    private javax.swing.JTextField q2TXT;
    private javax.swing.JTextField q3TXT;
    private javax.swing.JTextField q4TXT;
    private javax.swing.JTextField q5TXT;
    private javax.swing.JTextField q6TXT;
    private javax.swing.JToggleButton switchCategories;
    // End of variables declaration//GEN-END:variables
}
